name: transcendence
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      # Mount the source for hot reloads
      - ./frontend:/app
      # Anonymous volume that "masks" the mount above for this one path, keeping
      # the container's Linux-built node_modules instead of the host's
      - /app/node_modules
    # networks:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://transcendence:transcendence@database:5432/transcendence?schema=public
    ports:
      - "3000:3000"
    volumes:
      # Mount the source for hot reloads
      - ./backend:/app
      # Anonymous volume that "masks" the mount above for this one path, keeping
      # the container's Linux-built node_modules instead of the host's
      - /app/node_modules
      - ./database:/app/database:ro
    command: sh -c "npx prisma generate --schema=/app/database/prisma/schema.prisma && npm run start:dev"
    # environment:
    # secrets:
    # networks:
  database:
    container_name: database
    build:
      context: ./database
      target: development
    restart: unless-stopped
    env_file:
      - .env-example
    ports:
      - "5432:5432"
      - "5555:5555"
    volumes:
      - ./database:/app
      - /app/node_modules
      - database_data:/var/lib/postgresql/data
  # database:
  # container_name: database
  # image:
  # restart: unless-stopped
  # environment:
  # secrets:
  # volumes:
  # networks:

# secrets:

volumes:
  database_data:

networks:
  transcendence:
